### ISSUE TITLE
Slowly color change

### ISSUE THREAD

**Issue by trasigor** [MathewReiss/dithering#5]
Hi,

I'm tring to use this library to change one color to another one on the layer slowly, but can't get it work.
Can you please give an advice or instruction of how it can be done?

**Comment by MathewReiss** [comment]
Happy to help, but I can give better advice if I could see your source code :)

**Comment by trasigor** [comment]
Here is function I use to set layer color:

static void draw_background(Layer *layer, GContext *ctx) {
//   draw_transitioning_rect(ctx, layer_get_bounds(layer), GColorRed, GColorGreen);

  graphics_context_set_fill_color(ctx, GColorGreen);
  graphics_fill_rect(ctx, GRect(0, 0, 144, 168), 0, GCornerNone);
}

I commented out line where I tried to use your liblary to change color slowly.

**Comment by MathewReiss** [comment]
It looks like you are trying to pass in the second color as a string,
rather than repeating the same GColorFromHEX(HexStringToUInt("")) function.
Besides that, are you sure you are starting the timer correctly?

**Comment by trasigor** [comment]
You're right. I corrected the code after comment was sent.
Yep, all works fine if I just use
graphics_context_set_fill_color(ctx, GColorGreen);
but it's instantly change the color without any transitions as it of cause should be.
I was thinking... Will function draw_transitioning_rect(ctx, layer_get_bounds(layer), GColorRed, GColorGreen); work in the case when fill color should be changed? Also should be call any other function before or after this one so it worked?

**Comment by MathewReiss** [comment]
Are you calling start_transitioning_rect(layer, delay, repeat); when you
want to start the transition? If that still doesn't work, I'm afraid I'll
need to see more of your code to be able to help (the layer drawing
function and init should suffice).

**Comment by MathewReiss** [comment]
Also, the fill color will not make a difference. The library uses the
stroke color to draw each rect pixel by pixel.

**Comment by trasigor** [comment]
Added function start_transitioning_rect(layer, delay, repeat);
Also I added debug lines and see that function draw_dithered_rect calls twice with 100 persents first and then with 0 persents that is really strange.

**Comment by trasigor** [comment]
Wow. It started work little strange, but it is a progress.
Also in logs I see messages
[ERROR] app_timer.c:37: Timer 133 does not exist
What this error means?

**Comment by trasigor** [comment]
Thanks for help.
